{% set name = "disperse" %}
{% set version = "v0.9.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thierry-sousbie/DisPerSE/archive/master.tar.gz
  sha256: 3406f08470df454bc5428d18ec4828b8b683719cc8eddde52a29b91639f51771

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - openmp  # [osx]
  host:
    - gsl
    - cgal
    - libopenblas
    - gmp
    - openmp  # [osx]
    - _openmp_mutex  # [linux]

test:
  commands:
    - mse
    - fieldconv
    - netconv
    - skelconv

about:
  home: https://github.com/thierry-sousbie/DisPerSE
  summary: 'Automatic identification of persistent structures.'
  description: |
    DisPerSE stands for "Discrete Persistent Structures Extractor" and its main
    purpose is to identify persistent topological features such as peaks, voids,
    walls and in particular filamentary structures within sampled distributions
    in 2D, 3D, and possibly more...
  license: CECILL-C
  license_family: GPL2
  license_file: License.txt
  doc_url: https://www2.iap.fr/users/sousbie/web/html/indexd41d.html
  dev_url: https://github.com/thierry-sousbie/DisPerSE

extra:
  recipe-maintainers:
    - cphyc
